version: '3'

services: 
    rabbitmq-service:
        image: rabbitmq:3
        ports: 
            - 5672:5672
            
    elasticsearch-service:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        ports:
            - 9200:9200
            - 9300:9300
        environment: 
            - discovery.type=single-node


